INSERT INTO dbo.parties
(
    [name],
    [acronym],
    [representative],
    [logo_url],
    [list_position],
    [is_active]
)
VALUES
('Alianza Electoral Venceremos', 'AEV', 'RONALD DARWIN ATENCIO SOTOMAYOR', NULL, 1, 1),
('Partido Patriotico del Peru', 'PPP', 'HERBERT CALLER GUTIERREZ', NULL, 2, 1),
('Partido Civico Obras', 'PCO', 'RICARDO BELMONT CASSINELLI', NULL, 3, 1),
('Frente Popular Agricola FIA del Peru', 'FPA', 'SIN REPRESENTANTE', NULL, 4, 1),
('Partido Democrata Verde', 'PDV', 'ALEX GONZALES CASTILLO', NULL, 5, 1),
('Partido del Buen Gobierno', 'PBG', 'JORGE NIETO MONTESINOS', NULL, 6, 1),
('Partido Politico Peru Accion', 'PPA', 'FRANCISCO DIEZ CANSECO TAVARA', NULL, 7, 1),
('Partido Politico PRIN', 'PPP', 'WALTER GILMER CHIRINOS PURIZAGA', NULL, 8, 1),
('Partido Politico Progresemos', 'PPP', 'PAUL DAVIS JAIMES BLANCO', NULL, 9, 1),
('Partido Si Creo', 'PSC', 'ALFONSO CARLOS ESPA Y GARCES-ALVEAR', NULL, 10, 1),
('Partido Pais para Todos', 'PPT', 'CARLOS GONSALO ALVAREZ LOAYZA', NULL, 11, 1),
('Frente de la Esperanza 2021', 'FDE', 'LUIS FERNANDO OLIVERA VEGA', NULL, 12, 1),
('Partido Politica Nacional Peru Libre', 'PEL', 'VLADIMIR ROY CERRON ROJAS', NULL, 13, 1),
('Partido Ciudadanos por el Peru', 'CPP', 'SIN REPRESENTANTE', NULL, 14, 0),
('Primero la Gente - Comunidad, Ecologia, Libertad y Progreso', 'PLG', 'MARIA SOLEDAD PEREZ TELLO DE RODRIGUEZ', NULL, 15, 1),
('Partido Juntos Por el Peru', 'JPP', 'ROBERTO HELBERT SANCHEZ PALOMINO', NULL, 16, 1),
('Partido Politico Podemos Peru', 'PPP', 'JOSE LEON LUNA GALVEZ', NULL, 17, 1),
('Partido Democratico Federal', 'PDF', 'ARMANDO JOAQUIN MASSE FERNANDEZ', NULL, 18, 1),
('Partido Fe en el Peru', 'FEP', 'ALVARO GONZALO PAZ DE LA BARRA FREIGEIRO', NULL, 19, 1),
('Partido Politico Integridad Democratica', 'PID', 'WOLFGANG MARIO GROZO COSTA', NULL, 20, 1),
('Fuerza Popular', 'FUP', 'KEIKO SOFIA FUJIMORI HIGUCHI', NULL, 21, 1),
('Alianza para el Progreso', 'APP', 'CESAR ACUNA PERALTA', NULL, 22, 1),
('Partido Politico Cooperacion Popular', 'PCP', 'YONHY LESCANO ANCIETA', NULL, 23, 1),
('Ahora Nacion - AN', 'ANA', 'PABLO ALFONSO LOPEZ CHAU NAVA', NULL, 24, 1),
('Libertad Popular', 'LIP', 'RAFAEL JORGE BELAUNDE LLOSA', NULL, 25, 1),
('Un Camino Diferente', 'UCD', 'ROSARIO DEL PILAR FERNANDEZ BAZAN', NULL, 26, 1),
('Avanza Pais - Partido de Integracion Social', 'APA', 'JOSE DANIEL WILLIAMS ZAPATA', NULL, 27, 1),
('Peru Moderno', 'PEM', 'CARLOS ERNESTO JAICO CARRANZA', NULL, 28, 1),
('Partido Politico Peru Primero', 'PAP', 'MARIO ENRIQUE VIZCARRA CORNEJO', NULL, 29, 1),
('Salvemos al Peru', 'SAP', 'ANTONIO ORTIZ VILLANO', NULL, 30, 1),
('Partido Democratico Somos Peru', 'SPE', 'GEORGE PATRICK FORSYTH SOMMER', NULL, 31, 1),
('Partido Aprista Peruano', 'PAP', 'PITTER ENRIQUE VALDERRAMA PENA', NULL, 32, 1),
('Renovacion Popular', 'REP', 'RAFAEL BERNARDO LOPEZ ALIAGA CAZORLA', NULL, 33, 1),
('Partido Democrata Unido Peru', 'PDU', 'CHARLIE CARRASCO SALAZAR', NULL, 34, 1),
('Fuerza y Libertad', 'FYL', 'FIORELLA GIANNINA MOLINELLI ARISTONDO', NULL, 35, 1),
('Partido de los Trabajadores y Emprendedores - PTE', 'PTE', 'NAPOLEON BECERRA GARCIA', NULL, 36, 1),
('Unidad Nacional', 'UNA', 'ROBERTO ENRIQUE CHIABRA LEON', NULL, 37, 1),
('Partido Morado', 'PMO', 'MESIAS ANTONIO GUEVARA AMASIFUEN', NULL, 38, 1);
